# .github/workflows/example.yml

name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '* * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Baroonn'
          git config --global user.email 'bolubee95@gmail.com'

          git checkout master

          git remote add upstream https://github.com/hngx-org/team-eagle-zuri-portfolio-explore-backend.git
          git pull upstream master
